**Numpy**

In [2]:
import numpy as np

In [ ]:
# Buat matrix X ukuran 2x3
X = np.array([[1, 2, 3],
              [4, 5, 6]])

In [ ]:
print("Matrix X:")
print(X)

In [ ]:
# Tampilkan ukuran matrix
print("\nUkuran matrix X:", X.shape)

In [ ]:
# Kolom pertama
print("\nKolom pertama:")
print(X[:, 0])

In [ ]:
# Baris kedua
print("\nBaris kedua:")
print(X[1, :])

**Pytorch**

In [3]:
import torch

In [4]:
# Buat matrix X ukuran 2x3
X = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

In [5]:
print("Matrix X:")
print(X)

Matrix X:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
# Ukuran matrix
print("\nUkuran matrix X:", X.shape)


Ukuran matrix X: torch.Size([2, 3])


In [7]:
# Kolom pertama
print("\nKolom pertama:")
print(X[:, 0])


Kolom pertama:
tensor([1, 4])


In [8]:
# Baris kedua
print("\nBaris kedua:")
print(X[1, :])


Baris kedua:
tensor([4, 5, 6])


**Tensorflow**

In [10]:
import tensorflow as tf

In [11]:
# Buat matrix X ukuran 2x3
X = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

In [12]:
print("Matrix X:")
print(X)

Matrix X:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [13]:
# Ukuran matrix
print("\nUkuran matrix X:", X.shape)


Ukuran matrix X: (2, 3)


In [14]:
# Kolom pertama
print("\nKolom pertama:")
print(X[:, 0].numpy())


Kolom pertama:
[1 4]


In [15]:
# Baris kedua
print("\nBaris kedua:")
print(X[1, :].numpy())


Baris kedua:
[4 5 6]
