In [11]:
import numpy as np

In [13]:
# buat vector x dengan ukuran 3x1
x = np.array([30, 5, 10]) # type argument is optional, e.g.: dtype=np.float16
x

array([30,  5, 10])

In [14]:
# hitung panjang vector x
len(x)

3

In [17]:
# tampilkan ukuran vector x
x.shape

(3,)

In [18]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [19]:
# akses elemen pertama dari vector x
x[0] # zero-indexed

np.int64(30)

In [20]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

Vektor Transpose

lakukan transpose pada vector x dan simpan pada variabel x_t

In [21]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([30,  5, 10])

In [22]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [24]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[30, 5, 10]])
y

array([[30,  5, 10]])

In [49]:
# tampilkan ukuran dari vector x_t
x_t.shape

TensorShape([1, 3])

3 . Pytorch dan Tensorflow

In [50]:
import torch
import tensorflow as tf

In [51]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_pt = torch.tensor([30, 5, 10])
x_pt

tensor([30,  5, 10])

In [53]:
# tampilkan ukuran dari vector x_t
x_tf = tf.Variable([30, 5, 10])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([30,  5, 10], dtype=int32)>